name: cloud_portfolio_project
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^2.1.0
  responsive_builder: ^0.4.1
  font_awesome_flutter: ^9.1.0 
  url_launcher: ^6.0.9 
  flutter_feather_icons: ^2.0.0+1 
  cupertino_icons: ^1.0.2
  reactive_forms: ^14.1.0
  dio: ^4.0.6
  elegant_notification: ^1.6.3
  uuid: ^3.0.6
  flutter_markdown: ^0.6.13

dev_dependencies:
  flutter_test:
    sdk: flutter 

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  
  assets:
    - assets/files/
    - assets/screenshots/
    - assets/../README.md

  fonts:
    - family: Circe
      fonts:
        - asset: assets/fonts/circle/Circe-Thin.ttf
          weight: 200
        - asset: assets/fonts/circle/Circe-Light.ttf
          weight: 300
        - asset: assets/fonts/circle/Circe-Bold.ttf
          weight: 600
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/proxima_nova/ProximaNova-Thin.otf
          weight: 200
        - asset: assets/fonts/proxima_nova/ProximaNova-Regular.otf
          weight: 400
        - asset: assets/fonts/proxima_nova/ProximaNova-Bold.otf
          weight: 600 
